spring.application.name=PennyPal
jwt.secret=L+gCnVf6dHBWnQD1xwK0NmJMnRNQ22eJUHZRTLPEbjT6lnwfUNScl2Q4aeOqo2M1h6JCMzK1sZelZHYs1mNalQ==
jwt.expiration=86400000
spring.datasource.url=jdbc:mysql://localhost:3306/pennypal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect